CREATE TABLE COMPONY(
COMPANY_ID NUMBER PRIMARY KEY,
COMPANY_NAME VARCHAR2(100) NOT NULL,
COMPANY_ADDRESS  VARCHAR2(55),
COMPANY_PHONE VARCHAR2(20)
);
 
 ALTER TABLE COMPONY RENAME TO COMPANY;
 SELECT  * FROM COMPANY;
 
CREATE SEQUENCE COMPANY_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE
;

INSERT INTO COMPANY 
VALUES (company_seq.nextval,'햇에제과','서울시 강남구','02-1234-5676');

SELECT *FROM COMPANY;

INSERT INTO COMPANY
VALUES(company_seq.nextval,'롯에제과','서울시중구','02-2345-6789');

INSERT INTO COMPANY
VALUES(company_seq.nextval,'올이온','서울시용산구','02-3456-7890');

--SNACKS 테이블 생성
CREATE TABLE SNACKS (
SNACK_ID NUMBER(10,0) PRIMARY KEY,    --과자ID(기본키)
SNACK_NAME VARCHAR2(100) NOT NULL,  --과자이름(NULL불가)
PRICE NUMBER(10,2) NOT NULL,  --가격(NULL 불가)
COMPANY_ID NUMBER(10,0),    --회사ID(외래키)
CONSTRAINT COMPANY FOREIGN KEY(COMPANY_ID)
REFERENCES COMPANY(COMPANY_ID)
);

SELECT *FROM SNACKS;

--SNACKS 시쿼스 생성 SNACKS_SEQ
CREATE SEQUENCE SNACKS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE
;

INSERT INTO SNACKS
VALUES (SNACKS_SEQ.NEXTVAL,'오에스',1500,1);

INSERT INTO SNACKS
VALUES(snacks_seq.nextval,'칸조',1100,2);

INSERT INTO SNACKS
VALUES(snacks_seq.nextval,'조고파이',2000,2);

SELECT *FROM SNACKS;
















